#!/bin/sh
#SBATCH -A ngi2016001
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10-00:00:00
#SBATCH -J methylSeq__PROJECT_
#SBATCH -e _ANALYSISDIR_/_PROJECT_/logs/methylSeq_%j.log
#SBATCH -o _ANALYSISDIR_/_PROJECT_/logs/methylSeq_%j.log

# Source NGI environment
source /lupus/ngi/production/latest/conf/sourceme_upps.sh
source activate NGI

#set Nextflow env variables
export NXF_WORK=_ANALYSISDIR_/_PROJECT_/work

methylseq -resume --genome _GENOME_ \
    --reads '_DATADIR_/merged_fastqs__PROJECT_/*_R{1,2}.fastq.gz' \
    --outdir _ANALYSISDIR_/_PROJECT_/results
